cache: 
  paths:
    - node_modules/

stages:
  - .pre
  - build
  - test

prepare: 
  stage: .pre
  script: npm install
  tags: windows, linux, mac

win:build:
  stage: build
  script: npm run electron:build
  tags: windows

lin:build:
  stage: build
  script: npm run electron:build --linux

mac:build:
  stage: build
  script: npm run electron:build
  tags: mac

win:test:
  stage: test
  needs: ["win:build"]
  script: "if (Test-Path ./dist_electron) {return 0} else {return 1}"
  tags: windows