cache: 
  paths:
    - node_modules/

stages:
  - .pre
  - build
  - test

prepare: 
  stage: .pre
  script:
    - npm install
    - npm install -f node-aead-crypto

prepwin:
  stage: .pre
  script: 
    - (Get-Content -path .\node_modules\coap\lib\server.js) -creplace 'interface\)','_interface)' | Set-Content -Path .\node_modules\coap\lib\server.js
    - exit 0
  tags: [windows]

win:build:
  stage: build
  script:
    - npm run electron:build
    - "if (Test-Path ./dist_electron/win-unpacked/w-ade.exe) {exit 0} else {exit 1}"
  tags: [windows]
  artifacts:
    paths: ['./dist_electron/win-unpacked/','./dist_electron/w-ade*']

lin:build:
  stage: build
  script: 
    - npm run electron:build
  tags: [linux]

mac:build:
  stage: build
  script: npm run electron:build
  tags: [mac]
  